<a href="https://colab.research.google.com/github/kashyapsanket/Age-Detection-From-Blogs/blob/master/ClassificationModels_(Main).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
df = pd.read_csv('drive/My Drive/normalizedfeatures.csv')
df.head

<bound method NDFrame.head of         Unnamed: 0         0         1         2         3         4  \
0         0.000000  0.000277  0.000000  0.000000  0.000000  0.000000   
1         0.000001  0.000000  0.000000  0.000819  0.000000  0.000000   
2         0.000003  0.000277  0.000000  0.000000  0.000000  0.000000   
3         0.000004  0.000000  0.000000  0.000000  0.000000  0.000000   
4         0.000006  0.000000  0.000000  0.000000  0.000000  0.000000   
5         0.000007  0.000000  0.000000  0.000000  0.000000  0.000000   
6         0.000009  0.000000  0.000000  0.000000  0.000000  0.000000   
7         0.000010  0.000000  0.000000  0.001638  0.000000  0.000000   
8         0.000012  0.001662  0.001269  0.005733  0.000000  0.000000   
9         0.000013  0.000000  0.000000  0.000000  0.000000  0.000000   
10        0.000015  0.000277  0.000000  0.000000  0.000000  0.000000   
11        0.000016  0.000000  0.000000  0.000000  0.000000  0.000000   
12        0.000018  0.000277  0.00

In [0]:
#df['Unnamed: 0']
df.drop(['Unnamed: 0'], axis=1)
df.shape


(679319, 89)

In [0]:
df = df.drop(df.columns[0], axis=1)
df.head
df.shape

(679319, 88)

In [0]:
temp_df = pd.read_csv('drive/My Drive/BlogData.csv')
labels = temp_df['Age']

In [0]:
len(labels)

679319

In [0]:
df.shape

(679319, 88)

In [0]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

# encode class values as integers
encoder = LabelEncoder()
encoder.fit(labels)
encoded_Y = encoder.transform(labels)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [0]:
model = Sequential()
model.add(Dense(64, input_dim=88, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(3, activation='softmax'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model


In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 64)                5696      
_________________________________________________________________
dense_5 (Dense)              (None, 20)                1300      
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 63        
Total params: 7,059
Trainable params: 7,059
Non-trainable params: 0
_________________________________________________________________


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, dummy_y, test_size=0.3, random_state=42)


In [0]:
model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=250, batch_size=2048)

Train on 475523 samples, validate on 203796 samples
Epoch 1/250
475523/475523 [==============================] - 4s 8us/step - loss: 0.5969 - acc: 0.6728 - val_loss: 0.5792 - val_acc: 0.6870
Epoch 2/250
475523/475523 [==============================] - 4s 8us/step - loss: 0.5724 - acc: 0.6925 - val_loss: 0.5657 - val_acc: 0.6995
Epoch 3/250
475523/475523 [==============================] - 4s 8us/step - loss: 0.5642 - acc: 0.6999 - val_loss: 0.5608 - val_acc: 0.7024
Epoch 4/250
475523/475523 [==============================] - 4s 8us/step - loss: 0.5602 - acc: 0.7029 - val_loss: 0.5579 - val_acc: 0.7045
Epoch 5/250
475523/475523 [==============================] - 4s 8us/step - loss: 0.5578 - acc: 0.7043 - val_loss: 0.5556 - val_acc: 0.7058
Epoch 6/250
475523/475523 [==============================] - 4s 8us/step - loss: 0.5554 - acc: 0.7060 - val_loss: 0.5538 - val_acc: 0.7071
Epoch 7/250
475523/475523 [==============================] - 4s 8us/step - loss: 0.5541 - acc: 0.7068 - val_loss: 

In [0]:

from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [0]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df, temp_df['Age'], test_size=0.3, random_state=42)


In [0]:
y_train1

451301    20
161515    20
230654    30
12399     20
573830    10
505255    20
647399    10
347254    20
198501    30
262355    30
67472     10
292184    10
220838    10
571996    20
477871    10
390407    10
66371     10
119703    20
329210    20
66726     10
667121    20
412029    20
623211    20
133152    20
328873    10
46237     20
247689    10
348957    20
67736     30
609930    30
          ..
156730    10
500186    20
486232    20
258795    10
421909    20
347449    20
184779    10
214176    30
235796    20
103355    10
199041    20
327069    20
321879    20
64820     30
329365    10
41090     30
278167    30
191335    30
175203    30
87498     10
521430    30
137337    10
54886     10
110268    10
644167    10
259178    30
365838    20
131932    20
671155    20
121958    10
Name: Age, Length: 475523, dtype: int64

In [0]:

model1 = XGBClassifier()
model1.fit(X_train1, y_train1)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [0]:
y_pred = model1.predict(X_test1)
predictions = [round(value) for value in y_pred]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [0]:
accuracy = accuracy_score(y_test1, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 56.31%


In [0]:
X_test

0         1         2         3    4         5         6    7  \
637722  0.000277  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
153503  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
474581  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
280714  0.000277  0.000000  0.000000  0.000000  0.0  0.000000  0.002674  0.0   
40242   0.000277  0.000000  0.000000  0.000000  0.0  0.000000  0.002674  0.0   
507521  0.000277  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
613335  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.002674  0.0   
106263  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
273177  0.000277  0.000000  0.000000  0.000000  0.0  0.003268  0.000000  0.0   
70948   0.000277  0.000000  0.000000  0.011364  0.0  0.001089  0.000000  0.0   
618826  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
633584  0.000000  0.000000  0.000819  0.000000  0.0  0.000000  0.000000  0.0   
134232  0.001108  0.000000  0.001638  0.068182  0.0  0.004357  0.002674  0.0   
486357  0.000277  0.001269  0.009828  0.000000  0.0  0.013072  0.008021  0.0   
299116  0.000000  0.000000  0.000819  0.000000  0.0  0.000000  0.000000  0.0   
86238   0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
254545  0.000277  0.000000  0.000819  0.000000  0.0  0.000000  0.000000  0.0   
363669  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
435100  0.000277  0.000000  0.001638  0.000000  0.0  0.001089  0.000000  0.0   
33346   0.000554  0.000000  0.000000  0.000000  0.0  0.003268  0.000000  0.0   
542151  0.000277  0.000000  0.001638  0.000000  0.0  0.001089  0.000000  0.0   
313507  0.000831  0.000000  0.003276  0.000000  0.0  0.004357  0.002674  0.0   
256095  0.000277  0.000000  0.000819  0.000000  0.0  0.000000  0.000000  0.0   
164233  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
599650  0.000000  0.000000  0.000819  0.000000  0.0  0.000000  0.000000  0.0   
564809  0.000000  0.000000  0.000819  0.000000  0.0  0.003268  0.000000  0.0   
464659  0.000000  0.000000  0.001638  0.000000  0.0  0.002179  0.002674  0.0   
659383  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
286309  0.000000  0.001269  0.006552  0.000000  0.0  0.000000  0.000000  0.0   
566258  0.000277  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
...          ...       ...       ...       ...  ...       ...       ...  ...   
262636  0.000554  0.000000  0.000000  0.000000  0.0  0.001089  0.002674  0.0   
563952  0.000277  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
132     0.000000  0.000000  0.001638  0.000000  0.0  0.000000  0.002674  0.0   
53586   0.004985  0.001269  0.007371  0.000000  0.0  0.009804  0.010695  0.0   
404607  0.000000  0.000000  0.000000  0.011364  0.0  0.003268  0.000000  0.0   
314203  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
478773  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
263400  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
78666   0.000554  0.000000  0.000819  0.000000  0.0  0.003268  0.002674  0.0   
327667  0.000000  0.000000  0.002457  0.000000  0.0  0.002179  0.000000  0.0   
244457  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
59177   0.000554  0.000000  0.002457  0.011364  0.0  0.000000  0.000000  0.0   
203576  0.000000  0.000000  0.000819  0.000000  0.0  0.001089  0.002674  0.0   
560580  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.002674  0.0   
456192  0.000554  0.000000  0.000819  0.000000  0.0  0.000000  0.002674  0.0   
506788  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
561428  0.001385  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
255218  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  0.0   
64522   0.00027

In [0]:
pred = model.predict(X_test)

In [0]:
import numpy as np

use_y = []
use_pred = []
for i in range(len(pred)):
  use_y.append(np.argmax(y_test[i], axis=None, out=None))
  use_pred.append(np.argmax(pred[i], axis=None, out=None))
len(use_y)
len(use_pred)

203796

In [0]:
from sklearn.metrics import confusion_matrix
confusion_matrix(use_y, use_pred)

array([[39918, 30141,   665],
       [18992, 74574,  2624],
       [ 4315, 28050,  4517]])

In [0]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1]*100,"%")

Test loss: 0.5277031422241641
Test accuracy: 72.81922646054491 %


In [0]:
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import confusion_matrix

def ensembleclass(Xtrain, Ytrain, Xtest):
    print('Ho jaaye shuru')
    log_clf = LogisticRegression()
    rnd_clf = RandomForestClassifier()
    svm_clf = LinearSVC()

    voting_clf = VotingClassifier(estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],voting='hard')
    voting_clf.fit(Xtrain, Ytrain)
    Y_test = voting_clf.predict(Xtest)
    print("Please work")
    return Y_test

In [0]:
test_Y = ensembleclass(X_train, y_train1, X_test)


Ho jaaye shuru
Please work


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [0]:
def accuracy(x, y):
    print("Does it work?")
    counter = 0
    for i in range(len(x)):
        if x[i] == y[i]:
            counter = counter + 1
    print("We shall see")
    return (counter/len(x))*100

In [0]:
print(len(y_test1), len(test_Y))
acc = accuracy(list(y_test1), list(test_Y))
print(acc)
print(confusion_matrix(list(y_test1), list(test_Y)))

203796 203796
Does it work?
We shall see
54.222850301281674
[[31972 38724    28]
 [17638 78481    71]
 [ 4357 32474    51]]


In [0]:
def linear_svm(Xtrain, Ytrain, Xtest):
    rf = LinearSVC(max_iter=10000)
    rf.fit(Xtrain, Ytrain)
    Y_test = rf.predict(Xtest)
    return Y_test

In [0]:
svm_y = linear_svm(X_train, y_train1, X_test)
print(len(y_test1), len(svm_y))
acc = accuracy(list(y_test1), list(svm_y))
print(acc)
print(confusion_matrix(list(y_test1), list(svm_y)))

203796 203796
Does it work?
We shall see
54.076625645253095
[[31932 38759    33]
 [17895 78228    67]
 [ 4383 32453    46]]


In [0]:
def random_f(Xtrain, Ytrain, Xtest):
    rf = RandomForestClassifier()
    rf.fit(Xtrain, Ytrain)
    Y_test = rf.predict(Xtest)
    return Y_test

In [0]:
rf_y = random_f(X_train, y_train1, X_test)
print(len(y_test1), len(rf_y))
acc = accuracy(list(y_test1), list(rf_y))
print(acc)
print(confusion_matrix(list(y_test1), list(rf_y)))

203796 203796
Does it work?
We shall see
58.27052542738818
[[45142 23576  2006]
 [23091 66099  7000]
 [ 6769 22601  7512]]


In [0]:
def logistic_r(Xtrain, Ytrain, Xtest):
    rf = LogisticRegression()
    rf.fit(Xtrain, Ytrain)
    Y_test = rf.predict(Xtest)
    return Y_test

In [0]:
lr_y = logistic_r(X_train, y_train1, X_test)
print(len(y_test1), len(lr_y))
acc = accuracy(list(y_test1), list(lr_y))
print(acc)
print(confusion_matrix(list(y_test1), list(lr_y)))

203796 203796
Does it work?
We shall see
53.65414434041885
[[30652 40012    60]
 [17444 78618   128]
 [ 4291 32516    75]]
